#!/bin/bash 
	clear
    figlet W e l c ome           
  	echo "                                                       \|||/                                  "
	echo "                                .-.________            (o o)            _______.-.            "
	echo "                           ----/ \_)_______)  +--OooO---(_)---OooO--+  (_______(_/ \----      "
	echo "                              (    ()___)     | O s a m a E z N e   |     (___()     )        "
	echo "                                   ()__)      |                     |      (__()              "
	echo "                           ----\___()_)       |  www.osama-en.com   |       (_()___/----      "
	echo "                                              +--------OoooO--------+                         "
	echo "                                                                                              "
 	echo "                                        &--------------------------------&"
    echo "                                          Server Name is =>> $(hostname)"
    echo "                                        &--------------------------------&"
	echo "                                         ProcessID To programe < $$ >" 
	echo "                                                                                "
    echo "                                     &#######################################&  "
    echo "                                     |      Linux Distributions Report       |  "
    echo "                                     |                                       |  "
    echo "                                     &#######################################&  "
    echo "                                     | Name           Version       Released |  "
    echo "                                     +=======================================+  "
    echo "                                     |        |    |                         |  "
    echo "                                     | Fedora |dnf |  28 to 31    2019-12-6  |  "
    echo "                                     |--------|----|-------------------------|   "
    echo "                                     | Ubuntu |apt |  17 to 19    2019-12-6  |  "
    echo "                                     |--------|----|-------------------------|   "
   # echo "                                     | SUSE   |    |              2006-03-2  |  "
   # echo "                                      --------|----|------------------------    "
    echo "                                     | Kali   |apt |  17 to 19    2019-12-6  |  "
   # echo "                                      --------|----|------------------------    "
    #echo "                                     | archi  |    |              2006-03-2  |  "
    echo "                                     &#######################################&  "
	echo "                                                                                "
    echo "                                        Pless use program by root or sudo       "
    echo "                                                                                "
	echo "                                                  "
	while :
    do
    echo    "                                               "
	read -p "  ## Enter your name hostaname systeme # ~> " amr
    case $amr in
	apt | Ubuntu | ubuntu | kali | Kali | debian | apt-get| Apt | a | d) 
    /opt/OsEzNe/Debian/./Debian.sh #/home/ezrales/Desktop/OsEzNe/Action0/Debian/./Debian.sh #|| /*/*/*/*/./debian.sh
    ;;
    Fedora | fedora | rpm | dnf | yum | redhat | Redhat | Yum | y | f)
	/opt/OsEzNe/Redhat/./Redhat.sh #/home/ezrales/Desktop/OsEzNe/Action0/Redhat/./Redhat.sh #/home/*/*/*/*/*/./Redhat.sh #|| /*/*/*/*/./Redhat.sh
	;;
	exit)
	echo "                                               "
	break
	exit 0
	;;
	cle | clear)
	clear
	;;
	*)
	echo "                                      "
	echo "    ---------------------------------------"
	echo "        *  Pless Enter distory good  *"
	echo "    ---------------------------------------"
	echo "                                      "
	esac
	done
	#echo "  &--------------------------------& "
	#echo "   finish created file to .bashrc ..."
	#echo "  &--------------------------------& "
	#echo "                                     "
	#echo "                                     "
	#echo "                                     "
	#echo "          1.   | applications"
	#echo "          2.   | applications Graphices"
	#echo "          3.   | applications Ethical Hacking"
	#echo "          4.   | All applications"
	#echo "          0.   | Exit"
	#echo "                                       "
	#echo "                                       "
	
	#read -p "Enter Your number of [1 - 4]# :> " osama
   
    #case $osama in
    #0)
	#echo "                                           *** Bye! ***"
	#echo "                                                                                       "
	#echo "                 *******************************************************************   "
	#echo "                  *            My name is Osama Mohammed alzabidi                 *    "
	#echo "                 ******************************************************************* 	 "
	#exit 0
    #;;
    
    #4)
	
	#read -p "press [Enter] key to continuo...."
	#readEnterKey
	#;;
    
    #1) 
    #echo "                         "
    #echo "                         "
 	#echo " applications Graphices >"
    #echo "================================================================================="
    #echo "        |                                            |           |"        
    #echo "     1. |   krita                                    | 250 MB    |"  
	#echo "     2. |   sublime-text                             | 300 MB    |"
	#echo "     3. |   pycharm                                  | 300 MB    |"
	#echo "     4. |   All applications                         | ? MB      |"
	#echo "     0. |   Exit                                     | Exit      |"
    #echo "================================================================================="
    #echo "                                  "
